
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class addcourse extends javax.swing.JFrame {

    /**
     * Creates new form addcourse
     */
    public void getDepartmentnames(){
        try {

            HttpResponse<String> res = Unirest.get("http://localhost:8999/getdepartmentnames")
                    .asString();
            
            dnamecb.removeAllItems();

            if (res.getStatus() == 200) {
                String data = res.getBody();
                System.out.println(data);
                StringTokenizer st = new StringTokenizer(data, ":&");
                while (st.hasMoreTokens()) {
                    String departmentname = st.nextToken();
                    dnamecb.addItem(departmentname);  
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }
    public addcourse() {
        initComponents();
        setSize(1286, 750);
        setResizable(false);
        setLocationRelativeTo(null);
        semcb.removeAllItems();
        //semcb.addItem("");
        semcb.addItem("1st");
        semcb.addItem("2nd");
        semcb.addItem("3rd");
        semcb.addItem("4th");
        semcb.addItem("5th");
        semcb.addItem("6th");
        semcb.addItem("7th");
        semcb.addItem("8th");
        getDepartmentnames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cnametf = new javax.swing.JTextField();
        dnamecb = new javax.swing.JComboBox();
        semcb = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        cdescta = new javax.swing.JTextArea();
        addbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cnametf.setBackground(new java.awt.Color(0, 0, 0));
        cnametf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cnametf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(cnametf);
        cnametf.setBounds(870, 180, 330, 50);

        dnamecb.setBackground(new java.awt.Color(0, 0, 0));
        dnamecb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dnamecb.setForeground(new java.awt.Color(255, 255, 255));
        dnamecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(dnamecb);
        dnamecb.setBounds(870, 260, 330, 50);

        semcb.setBackground(new java.awt.Color(0, 0, 0));
        semcb.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        semcb.setForeground(new java.awt.Color(255, 255, 255));
        semcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        semcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semcbActionPerformed(evt);
            }
        });
        getContentPane().add(semcb);
        semcb.setBounds(870, 340, 330, 50);

        cdescta.setBackground(new java.awt.Color(0, 0, 0));
        cdescta.setColumns(20);
        cdescta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cdescta.setForeground(new java.awt.Color(255, 255, 255));
        cdescta.setRows(5);
        jScrollPane1.setViewportView(cdescta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(870, 420, 330, 110);

        addbtn.setBackground(new java.awt.Color(51, 255, 255));
        addbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addbtn.setForeground(new java.awt.Color(0, 102, 102));
        addbtn.setText("Add ");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn);
        addbtn.setBounds(1060, 570, 140, 50);

        backbtn.setBackground(new java.awt.Color(255, 0, 0));
        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(870, 570, 140, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/AddCourses.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            String cn = cnametf.getText();
            String dn = dnamecb.getSelectedItem().toString();
            String sem = semcb.getSelectedItem().toString();
            String desc = cdescta.getText();
            if (cn.equals("") || dn.equals("") || sem.equals("") || desc.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
                
            } else {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/addcourse")
                        .queryString("coursename", cn)
                        .queryString("departmentname", dn)
                        .queryString("semester", sem)
                        .queryString("description", desc)
                        .asString();

                if (res.getStatus() == 200) {
                    String responsetext = res.getBody();
                    if (responsetext.equals("success")) {
                        JOptionPane.showMessageDialog(this, "Course added successfuly");
                        cnametf.setText("");
                        cdescta.setText("");

                    } else {
                        JOptionPane.showMessageDialog(this, "Course Name already exist");
                    }

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void semcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semcbActionPerformed
        semcb.getSelectedItem();
    }//GEN-LAST:event_semcbActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose();
        new adminhome().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addcourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextArea cdescta;
    private javax.swing.JTextField cnametf;
    private javax.swing.JComboBox dnamecb;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox semcb;
    // End of variables declaration//GEN-END:variables
}
