
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class adddeept extends javax.swing.JFrame {

    /**
     * Creates new form adddeept
     */
    public adddeept() {
        initComponents();
        setSize(1286, 750);
        setResizable(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        hodnametf = new javax.swing.JTextField();
        phnnotf = new javax.swing.JTextField();
        emailtf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        despta = new javax.swing.JTextArea();
        addbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        dntf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        hodnametf.setBackground(new java.awt.Color(0, 0, 0));
        hodnametf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hodnametf.setForeground(new java.awt.Color(255, 255, 255));
        hodnametf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hodnametfActionPerformed(evt);
            }
        });
        getContentPane().add(hodnametf);
        hodnametf.setBounds(840, 230, 332, 50);

        phnnotf.setBackground(new java.awt.Color(0, 0, 0));
        phnnotf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phnnotf.setForeground(new java.awt.Color(255, 255, 255));
        phnnotf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnnotfActionPerformed(evt);
            }
        });
        getContentPane().add(phnnotf);
        phnnotf.setBounds(840, 300, 332, 40);

        emailtf.setBackground(new java.awt.Color(0, 0, 0));
        emailtf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailtf.setForeground(new java.awt.Color(255, 255, 255));
        emailtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtfActionPerformed(evt);
            }
        });
        getContentPane().add(emailtf);
        emailtf.setBounds(840, 360, 332, 40);

        despta.setBackground(new java.awt.Color(0, 0, 0));
        despta.setColumns(20);
        despta.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        despta.setForeground(new java.awt.Color(255, 255, 255));
        despta.setRows(5);
        jScrollPane1.setViewportView(despta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(840, 420, 332, 100);

        addbtn.setBackground(new java.awt.Color(51, 255, 255));
        addbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addbtn.setForeground(new java.awt.Color(0, 102, 102));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addbtn);
        addbtn.setBounds(1029, 580, 140, 69);

        backbtn.setBackground(new java.awt.Color(255, 0, 0));
        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(840, 580, 141, 69);

        dntf.setBackground(new java.awt.Color(0, 0, 0));
        dntf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dntf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(dntf);
        dntf.setBounds(840, 170, 332, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/AddDepartments.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public boolean isValidContact(String str){
        Pattern ptrn = Pattern.compile("(0/91)?[1-9][0-9]{9}");
        Matcher match = ptrn.matcher(str);
        return (match.find()&&match.group().equals(str));
    }
    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        try {
            String cbdept = dntf.getText();
            String hodname = hodnametf.getText();
            String phnno = phnnotf.getText();
            String email = emailtf.getText();
            String desp = despta.getText();
            if (cbdept.equals("") || hodname.equals("") || phnno.equals("") || email.equals("") || desp.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
                if (isValidContact(phnno) || phnno.length()>12 || (!email.contains("@") || !email.contains("."))) {
                    JOptionPane.showMessageDialog(this, "Please enter correct values");

                }
            } else {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/adddepartment")
                        .queryString("cbdept", cbdept)
                        .queryString("hodname", hodname)
                        .queryString("phnno", phnno)
                        .queryString("email", email)
                        .queryString("desp", desp)
                        .asString();

                if (res.getStatus() == 200) {
                    String responsetext = res.getBody();
                    if (responsetext.equals("success")) {
                        JOptionPane.showMessageDialog(this, "Department added successfuly");
                        dntf.setText("");
                        hodnametf.setText("");
                        emailtf.setText("");
                        phnnotf.setText("");
                        despta.setText("");

                    } else {
                        JOptionPane.showMessageDialog(this, "Department Name already exist");
                    }

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_addbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        this.dispose();
        new adminhome().setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void emailtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtfActionPerformed

    private void hodnametfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hodnametfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hodnametfActionPerformed

    private void phnnotfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnnotfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnnotfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddeept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddeept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddeept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddeept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adddeept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextArea despta;
    private javax.swing.JTextField dntf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JTextField hodnametf;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField phnnotf;
    // End of variables declaration//GEN-END:variables
}
