import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;


public class ForgotPasswordTeacher extends javax.swing.JFrame {

    String teacherid;
    String otp;
    
    public ForgotPasswordTeacher() {
        initComponents();
        setSize(1280,766);
        passpnl.setVisible(false);
        otppnl.setVisible(false);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idpnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idtf = new javax.swing.JTextField();
        submitbtn1 = new javax.swing.JButton();
        otppnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        otptf = new javax.swing.JTextField();
        submitbtn2 = new javax.swing.JButton();
        passpnl = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cppf = new javax.swing.JPasswordField();
        nppf = new javax.swing.JPasswordField();
        cpbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        idpnl.setBackground(new java.awt.Color(51, 51, 51));
        idpnl.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teacher ID");
        idpnl.add(jLabel2);
        jLabel2.setBounds(30, 20, 170, 30);
        idpnl.add(idtf);
        idtf.setBounds(140, 20, 410, 40);

        submitbtn1.setBackground(new java.awt.Color(0, 255, 204));
        submitbtn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        submitbtn1.setForeground(new java.awt.Color(0, 0, 204));
        submitbtn1.setText("Submit");
        submitbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn1ActionPerformed(evt);
            }
        });
        idpnl.add(submitbtn1);
        submitbtn1.setBounds(150, 80, 250, 50);

        getContentPane().add(idpnl);
        idpnl.setBounds(40, 110, 580, 160);

        otppnl.setBackground(new java.awt.Color(51, 51, 51));
        otppnl.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("OTP");
        otppnl.add(jLabel3);
        jLabel3.setBounds(30, 40, 150, 30);
        otppnl.add(otptf);
        otptf.setBounds(140, 30, 410, 40);

        submitbtn2.setBackground(new java.awt.Color(0, 255, 204));
        submitbtn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        submitbtn2.setForeground(new java.awt.Color(0, 0, 204));
        submitbtn2.setText("Submit");
        submitbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtn2ActionPerformed(evt);
            }
        });
        otppnl.add(submitbtn2);
        submitbtn2.setBounds(150, 90, 250, 50);

        getContentPane().add(otppnl);
        otppnl.setBounds(40, 280, 580, 180);

        passpnl.setBackground(new java.awt.Color(51, 51, 51));
        passpnl.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Confirm password");
        passpnl.add(jLabel4);
        jLabel4.setBounds(30, 100, 200, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter New Password");
        passpnl.add(jLabel5);
        jLabel5.setBounds(30, 40, 200, 30);
        passpnl.add(cppf);
        cppf.setBounds(190, 90, 350, 40);
        passpnl.add(nppf);
        nppf.setBounds(190, 30, 350, 40);

        cpbtn.setBackground(new java.awt.Color(0, 255, 204));
        cpbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        cpbtn.setForeground(new java.awt.Color(0, 0, 204));
        cpbtn.setText("Change Password");
        cpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpbtnActionPerformed(evt);
            }
        });
        passpnl.add(cpbtn);
        cpbtn.setBounds(160, 160, 240, 50);

        getContentPane().add(passpnl);
        passpnl.setBounds(40, 470, 580, 240);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(920, 450, 140, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/forgotPasswordAll.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1330, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn1ActionPerformed
        try {
            String sid = idtf.getText();
            teacherid = sid;
            if (teacherid.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Teacher ID");
            } else {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/TeacherForgotPassword1")
                .queryString("teacherid", sid)
                .asString();
                if (res.getStatus() == 200) {
                    String responsetext = res.getBody();
                    System.out.println(responsetext);
                    HttpResponse<String> res1 = Unirest.get("http://localhost:8999/GenerateOTPTeacher")
                            .queryString("teacherid", sid)
                    .asString();
                    if (res1.getStatus() == 200) {
                        String data = res1.getBody();
                        otp = data;
                        System.out.println("otp" + otp);
                        JOptionPane.showMessageDialog(this, "An OTP has been sent to your mobile no. for verification");
                        otppnl.setVisible(true);

                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Invalid Teacher ID");

                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitbtn1ActionPerformed

    private void submitbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtn2ActionPerformed
        try {
            String eotp = otptf.getText();
            if (eotp.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter OTP");
            } else {
                if (eotp.equals(otp)) {
                    JOptionPane.showMessageDialog(this, "OTP Matched");
                    passpnl.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Invalid OTP");

                }

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitbtn2ActionPerformed

    private void cpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpbtnActionPerformed
        String newpass = new String(nppf.getPassword());
        String confpass = new String(cppf.getPassword());
        try {
            if (newpass.equals("") || confpass.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
            } else if (newpass.equals(confpass)) {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/TeacherForgotPassword2")
                .queryString("teacherid", teacherid)
                .queryString("newpass", newpass)
                .asString();
                if (res.getStatus() == 200) {
                    String responsetext = res.getBody();
                    System.out.println(responsetext);
                    if (responsetext.equals("success")) {
                        JOptionPane.showMessageDialog(this, "Password Changed Successfully. You can now login with your new password");
                        this.dispose();
                        new TeacherLogin().setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(this, "Unable to change Password");

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "New Password and confirm password does not match");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cpbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new TeacherLogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordTeacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordTeacher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cpbtn;
    private javax.swing.JPasswordField cppf;
    private javax.swing.JPanel idpnl;
    private javax.swing.JTextField idtf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField nppf;
    private javax.swing.JPanel otppnl;
    private javax.swing.JTextField otptf;
    private javax.swing.JPanel passpnl;
    private javax.swing.JButton submitbtn1;
    private javax.swing.JButton submitbtn2;
    // End of variables declaration//GEN-END:variables
}
