/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class InteractUponHome extends javax.swing.JFrame {

    /**
     * Creates new form InteractUponHome
     */
    public InteractUponHome() {
        initComponents();
        setSize(1280,766);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        agdlbl = new javax.swing.JLabel();
        dvlbl = new javax.swing.JLabel();
        loginlb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/ihhome.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        agdlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agdlblMouseClicked(evt);
            }
        });
        getContentPane().add(agdlbl);
        agdlbl.setBounds(230, 290, 190, 60);

        dvlbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dvlblMouseClicked(evt);
            }
        });
        getContentPane().add(dvlbl);
        dvlbl.setBounds(520, 410, 280, 50);

        loginlb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginlbMouseClicked(evt);
            }
        });
        getContentPane().add(loginlb);
        loginlb.setBounds(950, 490, 160, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginlbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginlbMouseClicked
        new mainpage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginlbMouseClicked

    private void dvlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dvlblMouseClicked
        new Developers().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dvlblMouseClicked

    private void agdlblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agdlblMouseClicked
        new Agenda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agdlblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InteractUponHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InteractUponHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InteractUponHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InteractUponHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InteractUponHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agdlbl;
    private javax.swing.JLabel dvlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginlb;
    // End of variables declaration//GEN-END:variables
}
