
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class StudentChangePassword extends javax.swing.JFrame {
    String studentid;

    
    public StudentChangePassword(String sid) {
        initComponents();
        setSize(1280,766);
        sidtf.setEditable(false);
        sidtf.setText(sid);
        studentid = sid;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidtf = new javax.swing.JTextField();
        confpasspf = new javax.swing.JPasswordField();
        oldpasspf = new javax.swing.JPasswordField();
        newpasspf = new javax.swing.JPasswordField();
        bkbtn = new javax.swing.JButton();
        changebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(sidtf);
        sidtf.setBounds(330, 140, 380, 50);
        getContentPane().add(confpasspf);
        confpasspf.setBounds(330, 380, 380, 50);
        getContentPane().add(oldpasspf);
        oldpasspf.setBounds(330, 220, 380, 50);
        getContentPane().add(newpasspf);
        newpasspf.setBounds(330, 300, 380, 50);

        bkbtn.setBackground(new java.awt.Color(255, 0, 0));
        bkbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bkbtn.setForeground(new java.awt.Color(255, 255, 255));
        bkbtn.setText("Back");
        bkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bkbtn);
        bkbtn.setBounds(240, 490, 150, 50);

        changebtn.setBackground(new java.awt.Color(102, 255, 204));
        changebtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        changebtn.setForeground(new java.awt.Color(51, 0, 204));
        changebtn.setText("Change");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        getContentPane().add(changebtn);
        changebtn.setBounds(640, 490, 150, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/studentChangePassword.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
       String oldpass = new String(oldpasspf.getPassword());
        String newpass = new String(newpasspf.getPassword());
        String confpass = new String(confpasspf.getPassword());
        System.out.println(newpass);
        System.out.println(confpass);
        try {
            if (oldpass.equals("") || newpass.equals("") || confpass.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
            }else if(newpass.equals(confpass)) {
                    HttpResponse<String> res = Unirest.get("http://localhost:8999/changeStudentPassword")
                            .queryString("studentid", studentid)
                            .queryString("spassword", oldpass)
                            .queryString("newpass", newpass)
                            .asString();
                    if (res.getStatus() == 200) {
                        String responsetext = res.getBody();
                        System.out.println(responsetext);
                        if (responsetext.equals("success")) {
                            JOptionPane.showMessageDialog(this, "Password Changed Successfully. You can now login with your new password");
                            this.dispose();
                            new StudentLogin().setVisible(true);

                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid old password");

                        }
                    } 
            }else{
                JOptionPane.showMessageDialog(this, "New Password and confirm password does not match");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_changebtnActionPerformed

    private void bkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkbtnActionPerformed
        this.dispose();
        new studenthome(studentid).setVisible(true);
    }//GEN-LAST:event_bkbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StudentChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkbtn;
    private javax.swing.JButton changebtn;
    private javax.swing.JPasswordField confpasspf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField newpasspf;
    private javax.swing.JPasswordField oldpasspf;
    private javax.swing.JTextField sidtf;
    // End of variables declaration//GEN-END:variables
}
