
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class TeacherLogin extends javax.swing.JFrame {

    /**
     * Creates new form TeacherLogin
     */
    public TeacherLogin() {
        initComponents();
        setSize(1286, 750);
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tusertf = new javax.swing.JTextField();
        tpasspf = new javax.swing.JPasswordField();
        bkbtn = new javax.swing.JButton();
        loginbtn = new javax.swing.JButton();
        fplbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tusertf.setBackground(new java.awt.Color(0, 0, 0));
        tusertf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tusertf.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tusertf);
        tusertf.setBounds(220, 280, 340, 50);

        tpasspf.setBackground(new java.awt.Color(0, 0, 0));
        tpasspf.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tpasspf.setForeground(new java.awt.Color(255, 255, 255));
        tpasspf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpasspfActionPerformed(evt);
            }
        });
        getContentPane().add(tpasspf);
        tpasspf.setBounds(220, 370, 340, 50);

        bkbtn.setBackground(new java.awt.Color(255, 0, 0));
        bkbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bkbtn.setForeground(new java.awt.Color(255, 255, 255));
        bkbtn.setText("Back");
        bkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bkbtn);
        bkbtn.setBounds(120, 530, 170, 60);

        loginbtn.setBackground(new java.awt.Color(51, 255, 255));
        loginbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        loginbtn.setForeground(new java.awt.Color(0, 102, 102));
        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(340, 530, 170, 60);

        fplbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fplbl.setForeground(new java.awt.Color(255, 51, 0));
        fplbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fplblMouseClicked(evt);
            }
        });
        getContentPane().add(fplbl);
        fplbl.setBounds(170, 440, 340, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/TeacherLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
         try {

            String teacherid = tusertf.getText();
            String password = new String(tpasspf.getPassword());

            if (teacherid.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
            } else {
                HttpResponse<String> res = Unirest.get("http://localhost:8999/Teacherlogin")
                        .queryString("teacherid", teacherid)
                        .queryString("password", password)
                        .asString();
                if (res.getStatus() == 200) {
                    String responsetext = res.getBody();
                    if (responsetext.equals("success")) {
                        JOptionPane.showMessageDialog(this, "Login Successful");
                        new Teacherhome(teacherid).setVisible(true);
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, "Invalid Teacherid/password");

                    }

                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_loginbtnActionPerformed

    private void fplblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fplblMouseClicked
        fplbl.setForeground(Color.blue);
        new ForgotPasswordTeacher().setVisible(true);
    }//GEN-LAST:event_fplblMouseClicked

    private void tpasspfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpasspfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpasspfActionPerformed

    private void bkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkbtnActionPerformed
        this.dispose();
        new mainpage().setVisible(true);
    }//GEN-LAST:event_bkbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkbtn;
    private javax.swing.JLabel fplbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField tpasspf;
    private javax.swing.JTextField tusertf;
    // End of variables declaration//GEN-END:variables
}
