
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Lenovo
 */
public class TeacherChangePassword extends javax.swing.JFrame {

    String teacherid;

    public TeacherChangePassword(String tid) {
        initComponents();
        setSize(1280,766);
        tidtf.setEditable(false);
        tidtf.setText(tid);
        teacherid = tid;
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        tidtf = new javax.swing.JTextField();
        confpasspf = new javax.swing.JPasswordField();
        oldpasspf = new javax.swing.JPasswordField();
        newpasspf = new javax.swing.JPasswordField();
        changebtn = new javax.swing.JButton();
        bkbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(tidtf);
        tidtf.setBounds(320, 140, 350, 50);
        getContentPane().add(confpasspf);
        confpasspf.setBounds(320, 380, 350, 50);
        getContentPane().add(oldpasspf);
        oldpasspf.setBounds(320, 220, 350, 50);
        getContentPane().add(newpasspf);
        newpasspf.setBounds(320, 300, 350, 50);

        changebtn.setBackground(new java.awt.Color(0, 255, 204));
        changebtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        changebtn.setForeground(new java.awt.Color(0, 0, 153));
        changebtn.setText("Change");
        changebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changebtnActionPerformed(evt);
            }
        });
        getContentPane().add(changebtn);
        changebtn.setBounds(610, 530, 150, 50);

        bkbtn.setBackground(new java.awt.Color(255, 0, 0));
        bkbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bkbtn.setForeground(new java.awt.Color(255, 255, 255));
        bkbtn.setText("Back");
        bkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bkbtn);
        bkbtn.setBounds(220, 530, 150, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/teacherChangePassword.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1290, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changebtnActionPerformed
        String oldpass = new String(oldpasspf.getPassword());
        String newpass = new String(newpasspf.getPassword());
        String confpass = new String(confpasspf.getPassword());
        System.out.println(newpass);
        System.out.println(confpass);
        try {
            if (oldpass.equals("") || newpass.equals("") || confpass.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter values");
            }else if(newpass.equals(confpass)) {
                    HttpResponse<String> res = Unirest.get("http://localhost:8999/changeTeacherPassword")
                            .queryString("teacherid", teacherid)
                            .queryString("tpassword", oldpass)
                            .queryString("newpass", newpass)
                            .asString();
                    if (res.getStatus() == 200) {
                        String responsetext = res.getBody();
                        System.out.println(responsetext);
                        if (responsetext.equals("success")) {
                            JOptionPane.showMessageDialog(this, "Password Changed Successfully. You can now login with your new password");
                            this.dispose();
                            new TeacherLogin().setVisible(true);

                        } else {
                            JOptionPane.showMessageDialog(this, "Invalid old password");

                        }
                    } 
            }else{
                JOptionPane.showMessageDialog(this, "New Password and confirm password does not match");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_changebtnActionPerformed

    private void bkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkbtnActionPerformed
        this.dispose();
        new Teacherhome(teacherid).setVisible(true);
    }//GEN-LAST:event_bkbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TeacherChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkbtn;
    private javax.swing.JButton changebtn;
    private javax.swing.JPasswordField confpasspf;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField newpasspf;
    private javax.swing.JPasswordField oldpasspf;
    private javax.swing.JTextField tidtf;
    // End of variables declaration//GEN-END:variables
}
