/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class ViewNotesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewNotesPanel
     */
    public ViewNotesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        polb = new javax.swing.JLabel();
        titlelb = new javax.swing.JLabel();
        pblb = new javax.swing.JLabel();
        vdbtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(204, 255, 0));
        setLayout(null);

        polb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        polb.setForeground(new java.awt.Color(51, 153, 0));
        polb.setText("Posted On");
        add(polb);
        polb.setBounds(40, 120, 470, 60);

        titlelb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlelb.setForeground(new java.awt.Color(0, 153, 51));
        titlelb.setText("Title");
        add(titlelb);
        titlelb.setBounds(40, 20, 470, 60);

        pblb.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        pblb.setForeground(new java.awt.Color(51, 153, 0));
        pblb.setText("Posted By");
        add(pblb);
        pblb.setBounds(40, 70, 470, 60);

        vdbtn.setBackground(new java.awt.Color(0, 153, 0));
        vdbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        vdbtn.setForeground(new java.awt.Color(255, 255, 102));
        vdbtn.setText("View Details");
        add(vdbtn);
        vdbtn.setBounds(490, 60, 220, 70);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel pblb;
    public javax.swing.JLabel polb;
    public javax.swing.JLabel titlelb;
    public javax.swing.JButton vdbtn;
    // End of variables declaration//GEN-END:variables
}
